version: '2.2'
services:
  app:
    image: backend
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8082:8082"
    links:
      - apppostgres

  apppostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
